In [ ]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([ [3, 4, 5, 6, 7], [6, 7, 8, 9, 2] ])
ones = np.ones(5)
print(a1)
print(a2)
print(ones)

In [ ]:
# Arithmetic
print(a1 + ones)
print(a1 - ones)
print(a1 * ones)
print(a1 * a2)
print(a1 / a2)
print(a1 // a2)
print(a1 ** a2)

print("------------")
print(np.square(a1))
print(np.add(a1, ones))
print(np.mod(a1, ones))


In [ ]:
# Aggregation - performing the same operation on a number of things
my_array = np.array([5, 43, 23, 12, 21, 23])

print(sum(my_array))
print(np.sum(my_array))

# NB: Use Python's methods on Python datatypes and use NumPy's methods on NumPy arrays


127
127


In [21]:
# Creating a massive NumPy array
massive_array = np.random.random(100000)
massive_array[:10]

array([0.68218497, 0.78012409, 0.93935702, 0.27493592, 0.86285338,
       0.51521103, 0.89629094, 0.97207734, 0.31598612, 0.1902271 ])

In [22]:
%timeit (sum(massive_array))
%timeit np.sum(massive_array)

24.9 ms ± 2.56 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
188 μs ± 34.7 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
print(np.mean(massive_array))
print(np.max(massive_array))
print(np.min(massive_array))
print(np.std(massive_array))
# Standard deviation - how spread out a group of numbers is from the mean (square root of variance)
print(np.sqrt(np.var(massive_array)))
print(np.var(massive_array))
# Variance is the measure of the average degree to which each number is different to the mean

0.5006926182108296
0.9999530948941195
2.0322607752754074e-05
0.28916719567409666
0.28916719567409666
0.08361766705402131


In [34]:
# Reshaping & Transposing
array1 = np.array([[2, 3, 4], [6, 7, 8]])
array2 = np.array([ [[5, 6, 7], [12, 11, 32], [12, 11, 54]], [[23, 32, 12], [12, 43, 54], [67, 65, 43]] ])

array1.shape, array2.shape

((2, 3), (2, 3, 3))

In [41]:
array1_reshape = array1.reshape(2, 3, 1)
print(array1_reshape, array1_reshape.shape)
array1_reshape * array2

[[[2]
  [3]
  [4]]

 [[6]
  [7]
  [8]]] (2, 3, 1)


array([[[ 10,  12,  14],
        [ 36,  33,  96],
        [ 48,  44, 216]],

       [[138, 192,  72],
        [ 84, 301, 378],
        [536, 520, 344]]])

In [44]:
# Transpose - switches the axis
print(array1)
array1.T


[[2 3 4]
 [6 7 8]]


array([[2, 6],
       [3, 7],
       [4, 8]])

In [46]:
# Dot product
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))
mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [ ]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [51]:
mat3 = np.dot(mat1, mat2.T)
mat3, mat3.shape

(array([[ 51,  55,  72,  20,  15],
        [130,  76, 164,  33,  44],
        [ 67,  39,  85,  27,  34],
        [115,  69, 146,  37,  47],
        [111,  77, 145,  56,  64]]),
 (5, 5))

In [ ]:
# Comparison Operators
mat1 > mat2
mat1 >= mat2
mat1 == mat2
mat1 <= mat2
mat1 != mat2
mat1 < mat2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [60]:
# Sorting Arrays
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6],
       [8, 4, 1, 4, 9]])

In [61]:
np.sort(random_array)

array([[0, 2, 2, 3, 7],
       [0, 4, 5, 5, 6],
       [1, 4, 4, 8, 9]])

In [62]:
np.argsort(random_array)

array([[4, 1, 3, 0, 2],
       [0, 1, 2, 3, 4],
       [2, 1, 3, 0, 4]])

In [63]:
new_array = np.array([1, 5, 2, 9])
np.argsort(new_array)

array([0, 2, 1, 3])

In [64]:
np.argmin(new_array)

np.int64(0)

In [65]:
np.argmax(new_array)

np.int64(3)

In [66]:
np.argmax(random_array, axis=0)

array([2, 1, 0, 1, 2])

In [68]:
np.argmin(random_array, axis=1)

array([4, 0, 2])

In [69]:
random_array

array([[3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6],
       [8, 4, 1, 4, 9]])

In [ ]:
# 